hwi_oauth:
#    connect:
#        account_connector: cocorico_user.oauth.user.provider.entity
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            options:
                display: popup
                csrf: true
            #todo: Submit app review to facebook to get user_location user_hometown user_birthday
            #scope:         "public_profile, user_birthday, user_friends, user_location, user_hometown"
            #infos_url:     "https://graph.facebook.com/me?fields=id,link,name,email,first_name,last_name,verified,gender,birthday,locale,timezone,picture.height(500).width(500),address,location,hometown,friends"
            scope:         "public_profile"
            infos_url:     "https://graph.facebook.com/me?fields=id,link,name,email,first_name,last_name,verified,gender,locale,timezone,picture.height(500).width(500)"

            #            options:
            #                display: popup #dialog is optimized for popup window
            paths:
                profilepicture: picture.data.url

services:
    cocorico_user.oauth.user.provider.entity:
        class: Cocorico\UserBundle\Security\OAuthUserProvider
        arguments:
            - '@cocorico_user.user_manager'

    cocorico_user.user_manager:
        class: Cocorico\UserBundle\Model\UserManager
        arguments:
            - '@fos_user.util.password_updater'
            - '@fos_user.util.canonical_fields_updater'
            - '@fos_user.object_manager'
            - '%fos_user.model.user.class%'
            - '%kernel.root_dir%'
            - '@event_dispatcher'
            - '%cocorico.time_unit%'
            - '%cocorico.time_zone%'
        public: true
