fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_message:
#    resource: "@FOSMessageBundle/Resources/config/routing.xml"
#    prefix: /optional_routing_prefix

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"


hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /login

hwi_facebook_login:
    path: /oauth/fb-login

oneup_uploader:
    resource: .
    type: uploader
